# name: Deploy Project

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to Server
#         uses: appleboy/ssh-action@v0.1.6
#         with:
#           host: ${{ secrets.HOST }}
#           username: ubuntu
#           key: ${{ secrets.SSH_KEY }}
#           script: |
#             cd calculator-devops-project 
#             git pull
#             docker build -t final-app .
#             docker stop app || true
#             docker rm app || true
#             docker run -d -p 80:80 --name app final-app



name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Go to home directory
            cd ~

            # Clone repo if not exists
            if [ ! -d "calculator-devops-project" ]; then
              git clone https://github.com/phanis-git/calculator-devops-project.git
            fi

            # Go into repo
            cd calculator-devops-project

             chmod +x scripts/setup.sh
             ./scripts/setup.sh

            # Pull latest code
            git pull origin main

            # Build Docker image
            sudo docker build -t final-app .

            # Stop & remove old container
            sudo docker stop app || true
            sudo docker rm app || true

            # Run new container
            sudo docker run -d -p 80:80 --name app final-app